// Fonte: https://docs.google.com/spreadsheets/d/1fjQ1yCxnMmbufamaiudB6I0ESqE5S_vqp_k4PVHA4ak/edit
// Captura das abas Produtos (63 Dev Kits) e Sistemas ArtiSys (4 sistemas), em 09/10/2026.
// Apenas rascunhos; não ativa vendas, download ou entrega.
export const CATALOG_DRAFTS=Object.freeze([
  {
    "id": "artisys-qa",
    "productId": "artisys-qa",
    "name": "Testes e Controle de Qualidade",
    "description": "Executa testes de interface, evidências, demonstrações e validação visual opcional.",
    "priceCents": 3853,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "testes-e-controle-de-qualidade-v2.4.1.zip",
    "active": false
  },
  {
    "id": "artisys-security",
    "productId": "artisys-security",
    "name": "Segurança Automatizada",
    "description": "Verifica segredos expostos, vulnerabilidades e problemas estáticos de segurança.",
    "priceCents": 5405,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "seguranca-automatizada-v0.2.0.zip",
    "active": false
  },
  {
    "id": "artisys-api-contracts",
    "productId": "artisys-api-contracts",
    "name": "Contratos e Compatibilidade de APIs",
    "description": "Valida contratos de API, compatibilidade entre serviços e clientes gerados.",
    "priceCents": 5405,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "contratos-e-compatibilidade-de-apis-v0.2.0.zip",
    "active": false
  },
  {
    "id": "artisys-release",
    "productId": "artisys-release",
    "name": "Empacotamento e Publicação",
    "description": "Orquestra validações, assinatura, hashes e etapas necessárias para publicar uma versão.",
    "priceCents": 4473,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "empacotamento-e-publicacao-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-release-validator",
    "productId": "artisys-release-validator",
    "name": "Validação de Instaladores e Releases",
    "description": "Testa instaladores, atualização, stress e integridade antes da distribuição.",
    "priceCents": 5405,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "validacao-de-instaladores-e-releases-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-product-qa",
    "productId": "artisys-product-qa",
    "name": "Validação Completa do Produto",
    "description": "Agrupa QA, segurança e contratos de API para validar um produto de ponta a ponta.",
    "priceCents": 6957,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "validacao-completa-do-produto-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-ai-quality",
    "productId": "artisys-ai-quality",
    "name": "Testes e Qualidade de IA",
    "description": "Avalia prompts, respostas e regressões de funcionalidades que usam inteligência artificial.",
    "priceCents": 6957,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "testes-e-qualidade-de-ia-v0.2.0.zip",
    "active": false
  },
  {
    "id": "artisys-privacy",
    "productId": "artisys-privacy",
    "name": "Privacidade e Proteção de Dados",
    "description": "Detecta, anonimiza e mascara dados pessoais e informações sensíveis.",
    "priceCents": 6336,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "privacidade-e-protecao-de-dados-v0.2.0.zip",
    "active": false
  },
  {
    "id": "artisys-pdf",
    "productId": "artisys-pdf",
    "name": "Geração e Leitura de PDFs",
    "description": "Gera, visualiza, destaca e anota documentos PDF.",
    "priceCents": 3853,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "geracao-e-leitura-de-pdfs-v1.0.0.zip",
    "active": false
  },
  {
    "id": "artisys-media",
    "productId": "artisys-media",
    "name": "Áudio, Vídeo e Animações",
    "description": "Fornece operações reutilizáveis para mídia, áudio, vídeo e manifestos de animação.",
    "priceCents": 4473,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "audio-video-e-animacoes-v1.0.0.zip",
    "active": false
  },
  {
    "id": "artisys-office",
    "productId": "artisys-office",
    "name": "Documentos e Planilhas Office",
    "description": "Manipula documentos, planilhas e apresentações em formatos de escritório.",
    "priceCents": 4473,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "documentos-e-planilhas-office-v1.0.0.zip",
    "active": false
  },
  {
    "id": "artisys-annotations",
    "productId": "artisys-annotations",
    "name": "Anotações em Imagens e PDFs",
    "description": "Adiciona marcações e anotações reutilizáveis em imagens e documentos PDF.",
    "priceCents": 3853,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "anotacoes-em-imagens-e-pdfs-v1.0.0.zip",
    "active": false
  },
  {
    "id": "artisys-documents",
    "productId": "artisys-documents",
    "name": "Leitura e Processamento de Documentos",
    "description": "Extrai e processa conteúdo de documentos e imagens com OCR e visão computacional.",
    "priceCents": 4784,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "leitura-e-processamento-de-documentos-v0.2.0.zip",
    "active": false
  },
  {
    "id": "artisys-video-engine",
    "productId": "artisys-video-engine",
    "name": "Processamento e Edição de Vídeo",
    "description": "Executa jobs e timelines locais para processamento e composição de vídeo.",
    "priceCents": 5405,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "processamento-e-edicao-de-video-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-doc-convert",
    "productId": "artisys-doc-convert",
    "name": "Conversão de Documentos",
    "description": "Converte documentos entre formatos sob demanda, sem serviço externo obrigatório.",
    "priceCents": 3232,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "conversao-de-documentos-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-ocr",
    "productId": "artisys-ocr",
    "name": "Reconhecimento de Texto (OCR)",
    "description": "Oferece uma interface única para reconhecer texto em imagens e documentos.",
    "priceCents": 5405,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "reconhecimento-de-texto-ocr-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-workflows",
    "productId": "artisys-workflows",
    "name": "Fluxos de Trabalho Visuais",
    "description": "Modela fluxos, dependências e processos com editores visuais.",
    "priceCents": 6336,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "fluxos-de-trabalho-visuais-v1.0.0.zip",
    "active": false
  },
  {
    "id": "artisys-dashboard",
    "productId": "artisys-dashboard",
    "name": "Painéis e Indicadores",
    "description": "Monta dashboards, painéis redimensionáveis, grades e visualizações de dados.",
    "priceCents": 5405,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "paineis-e-indicadores-v1.0.0.zip",
    "active": false
  },
  {
    "id": "artisys-planning",
    "productId": "artisys-planning",
    "name": "Planejamento e Cronogramas",
    "description": "Gerencia Gantt, calendário, progresso, recursos e conflitos de planejamento.",
    "priceCents": 5405,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "planejamento-e-cronogramas-v1.0.0.zip",
    "active": false
  },
  {
    "id": "artisys-ui-builder",
    "productId": "artisys-ui-builder",
    "name": "Construtor de Interfaces",
    "description": "Cria páginas e blocos de interface editáveis e portáveis.",
    "priceCents": 6957,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "construtor-de-interfaces-v1.0.0.zip",
    "active": false
  },
  {
    "id": "artisys-capture",
    "productId": "artisys-capture",
    "name": "Captura por Câmera e Códigos",
    "description": "Captura câmera ou arquivo e lê QR codes, códigos de barras e imagens.",
    "priceCents": 3853,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "captura-por-camera-e-codigos-v1.0.0.zip",
    "active": false
  },
  {
    "id": "artisys-upload",
    "productId": "artisys-upload",
    "name": "Envio e Validação de Arquivos",
    "description": "Controla upload, políticas, validações, filas e seleção de arquivos.",
    "priceCents": 3232,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "envio-e-validacao-de-arquivos-v1.0.0.zip",
    "active": false
  },
  {
    "id": "artisys-files",
    "productId": "artisys-files",
    "name": "Organização e Exploração de Arquivos",
    "description": "Cria workspaces espelhados em pastas locais com árvore, drag-and-drop, busca e acompanhamento de alterações.",
    "priceCents": 3853,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "organizacao-e-exploracao-de-arquivos-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-serialport",
    "productId": "artisys-serialport",
    "name": "Integração com Dispositivos Seriais",
    "description": "Conecta balanças, gavetas e outros equipamentos por porta serial.",
    "priceCents": 5405,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "integracao-com-dispositivos-seriais-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-printing",
    "productId": "artisys-printing",
    "name": "Impressão, Cupons e Etiquetas",
    "description": "Gera e imprime recibos, cupons, etiquetas e saídas para impressoras térmicas.",
    "priceCents": 5405,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "impressao-cupons-e-etiquetas-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-remote-support",
    "productId": "artisys-remote-support",
    "name": "Suporte Remoto",
    "description": "Abre sessões controladas de suporte remoto para aplicativos desktop.",
    "priceCents": 5405,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "suporte-remoto-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-desktop-shell",
    "productId": "artisys-desktop-shell",
    "name": "Estrutura Base para Aplicativos Desktop",
    "description": "Padroniza estrutura desktop, deep links, configurações, logs e hooks de atualização.",
    "priceCents": 8509,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "estrutura-base-para-aplicativos-desktop-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-local-backend",
    "productId": "artisys-local-backend",
    "name": "Backend Local Embutido",
    "description": "Fornece backend local opcional para aplicações que precisam de API e persistência no próprio dispositivo.",
    "priceCents": 6957,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "backend-local-embutido-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-licensing",
    "productId": "artisys-licensing",
    "name": "Licenciamento Offline",
    "description": "Gerencia licenças locais, expiração, vínculo ao dispositivo e liberação de funcionalidades.",
    "priceCents": 6957,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "licenciamento-offline-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-eventbus",
    "productId": "artisys-eventbus",
    "name": "Comunicação entre Módulos",
    "description": "Permite que partes do sistema troquem eventos sem ficarem fortemente acopladas.",
    "priceCents": 4473,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "comunicacao-entre-modulos-v0.2.0.zip",
    "active": false
  },
  {
    "id": "artisys-alerts",
    "productId": "artisys-alerts",
    "name": "Alertas e Notificações",
    "description": "Gerencia alertas locais, vencimentos, severidade e notificações internas com estado lido/não lido.",
    "priceCents": 3232,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "alertas-e-notificacoes-v0.2.0.zip",
    "active": false
  },
  {
    "id": "artisys-backup",
    "productId": "artisys-backup",
    "name": "Backup e Restauração",
    "description": "Cria cópias de segurança verificáveis, retenção e checagem de integridade.",
    "priceCents": 5405,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "backup-e-restauracao-v0.2.0.zip",
    "active": false
  },
  {
    "id": "artisys-importer",
    "productId": "artisys-importer",
    "name": "Importação de Dados",
    "description": "Mapeia, pré-visualiza, valida, detecta duplicidades e coordena rollback de importações.",
    "priceCents": 4473,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "importacao-de-dados-v0.2.0.zip",
    "active": false
  },
  {
    "id": "artisys-auth-rbac",
    "productId": "artisys-auth-rbac",
    "name": "Acesso e Permissões",
    "description": "Gerencia autenticação local, usuários, papéis, permissões e proteção de ações.",
    "priceCents": 6957,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "acesso-e-permissoes-v0.2.0.zip",
    "active": false
  },
  {
    "id": "artisys-storage",
    "productId": "artisys-storage",
    "name": "Armazenamento de Dados",
    "description": "Padroniza armazenamento em memória, banco local e namespaces isolados.",
    "priceCents": 5405,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "armazenamento-de-dados-v0.2.1.zip",
    "active": false
  },
  {
    "id": "artisys-audit-log",
    "productId": "artisys-audit-log",
    "name": "Histórico e Auditoria",
    "description": "Registra quem realizou cada ação, em qual entidade e com quais metadados.",
    "priceCents": 5405,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "historico-e-auditoria-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-sync",
    "productId": "artisys-sync",
    "name": "Sincronização de Dados",
    "description": "Sincroniza alterações offline, aplica tentativas automáticas e resolve conflitos.",
    "priceCents": 6957,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "sincronizacao-de-dados-v0.2.0.zip",
    "active": false
  },
  {
    "id": "artisys-settings",
    "productId": "artisys-settings",
    "name": "Configurações do Sistema",
    "description": "Centraliza preferências, valores padrão e configurações separadas por namespace.",
    "priceCents": 3232,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "configuracoes-do-sistema-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-multitenancy",
    "productId": "artisys-multitenancy",
    "name": "Multiempresa e Isolamento de Dados",
    "description": "Separa empresas ou clientes e impede acesso indevido entre contextos diferentes.",
    "priceCents": 8509,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "multiempresa-e-isolamento-de-dados-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-feature-flags",
    "productId": "artisys-feature-flags",
    "name": "Ativação Controlada de Funcionalidades",
    "description": "Liga ou desliga recursos por padrão, empresa ou usuário sem duplicar código.",
    "priceCents": 4473,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "ativacao-controlada-de-funcionalidades-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-search",
    "productId": "artisys-search",
    "name": "Busca Local",
    "description": "Indexa e pesquisa entidades localmente com pesos, filtros e ranking determinístico.",
    "priceCents": 3232,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "busca-local-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-exporter",
    "productId": "artisys-exporter",
    "name": "Exportação de Dados",
    "description": "Exporta CSV e JSON e gera modelo tabular neutro para adaptadores de planilha.",
    "priceCents": 3232,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "exportacao-de-dados-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-pwa-runtime",
    "productId": "artisys-pwa-runtime",
    "name": "Aplicativo Web Instalável e Offline",
    "description": "Fornece cache, instalação, funcionamento offline e atualização controlada para PWAs.",
    "priceCents": 5405,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "aplicativo-web-instalavel-e-offline-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-webview-bridge",
    "productId": "artisys-webview-bridge",
    "name": "Integração Web ↔ Aplicativo",
    "description": "Padroniza a comunicação segura entre uma interface WebView e o aplicativo nativo.",
    "priceCents": 6336,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "integracao-web-aplicativo-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-whatsapp-launcher",
    "productId": "artisys-whatsapp-launcher",
    "name": "Abertura de Conversas no WhatsApp",
    "description": "Abre WhatsApp ou WhatsApp Web com número e mensagem pré-preenchidos, sem envio automático obrigatório.",
    "priceCents": 1990,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "abertura-de-conversas-no-whatsapp-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-finance-domain",
    "productId": "artisys-finance-domain",
    "name": "Motor Financeiro e Conciliação",
    "description": "Processa regras financeiras, duplicidades, transferências e conciliação de forma determinística.",
    "priceCents": 9999,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "motor-financeiro-e-conciliacao-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-inventory",
    "productId": "artisys-inventory",
    "name": "Estoque e Movimentações",
    "description": "Controla entradas, saídas, reservas, lotes, séries e saldo disponível.",
    "priceCents": 8509,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "estoque-e-movimentacoes-v0.2.0.zip",
    "active": false
  },
  {
    "id": "artisys-os",
    "productId": "artisys-os",
    "name": "Ordens de Serviço",
    "description": "Gerencia abertura, estados, transições e histórico de ordens de serviço.",
    "priceCents": 8509,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "ordens-de-servico-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-catalog",
    "productId": "artisys-catalog",
    "name": "Catálogo de Produtos e Serviços",
    "description": "Cadastra e organiza produtos, serviços, variantes, busca e ativação.",
    "priceCents": 6336,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "catalogo-de-produtos-e-servicos-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-pricing",
    "productId": "artisys-pricing",
    "name": "Preços, Descontos e Combos",
    "description": "Calcula preços por quantidade, faixas, descontos, combos e valores de linha.",
    "priceCents": 6336,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "precos-descontos-e-combos-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-checklists",
    "productId": "artisys-checklists",
    "name": "Checklists e Inspeções",
    "description": "Gerencia listas de verificação, evidências, progresso e conclusão.",
    "priceCents": 5405,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "checklists-e-inspecoes-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-reporting",
    "productId": "artisys-reporting",
    "name": "Relatórios e Indicadores",
    "description": "Aplica filtros, agrupamentos e agregações e exporta resultados para CSV.",
    "priceCents": 6957,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "relatorios-e-indicadores-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-workflow-engine",
    "productId": "artisys-workflow-engine",
    "name": "Motor de Fluxos de Trabalho",
    "description": "Executa máquinas de estado determinísticas com transições, guards e histórico.",
    "priceCents": 8509,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "motor-de-fluxos-de-trabalho-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-approvals",
    "productId": "artisys-approvals",
    "name": "Aprovações",
    "description": "Orquestra aprovações em múltiplas etapas, decisões, rejeições e histórico.",
    "priceCents": 5405,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "aprovacoes-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-contacts",
    "productId": "artisys-contacts",
    "name": "Contatos e Organizações",
    "description": "Normaliza pessoas, empresas, canais de contato, endereços e identificadores.",
    "priceCents": 5405,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "contatos-e-organizacoes-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-assets",
    "productId": "artisys-assets",
    "name": "Cadastro de Ativos",
    "description": "Cadastra ativos genéricos com situação, localização, responsável, tags e metadados.",
    "priceCents": 5405,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "cadastro-de-ativos-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-asset-lifecycle",
    "productId": "artisys-asset-lifecycle",
    "name": "Ciclo de Vida de Ativos",
    "description": "Registra aquisição, disponibilidade, manutenção, indisponibilidade e baixa de ativos.",
    "priceCents": 6957,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "ciclo-de-vida-de-ativos-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-custody",
    "productId": "artisys-custody",
    "name": "Custódia e Empréstimos",
    "description": "Controla retirada, responsável, prazo, devolução e condição de ativos.",
    "priceCents": 5405,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "custodia-e-emprestimos-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-maintenance",
    "productId": "artisys-maintenance",
    "name": "Manutenção Preventiva",
    "description": "Planeja manutenção por tempo ou medidor e calcula próximos vencimentos.",
    "priceCents": 6957,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "manutencao-preventiva-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-metering",
    "productId": "artisys-metering",
    "name": "Medidores e Leituras",
    "description": "Registra horímetro, odômetro, ciclos e outros medidores com deltas e validação.",
    "priceCents": 5405,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "medidores-e-leituras-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-bim",
    "productId": "artisys-bim",
    "name": "Leitura e Processamento BIM/IFC",
    "description": "Lê modelos IFC, propriedades, quantidades e informações reutilizáveis de projetos BIM.",
    "priceCents": 9999,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "leitura-e-processamento-bim-ifc-v0.2.0.zip",
    "active": false
  },
  {
    "id": "artisys-agro-maps",
    "productId": "artisys-agro-maps",
    "name": "Mapas e Dados Geoespaciais Agro",
    "description": "Valida, normaliza e prepara geometrias e mapas offline para produtos agrícolas e pecuários.",
    "priceCents": 8509,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "mapas-e-dados-geoespaciais-agro-v0.1.0.zip",
    "active": false
  },
  {
    "id": "artisys-agro-contract",
    "productId": "artisys-agro-contract",
    "name": "Integração e Contratos entre Sistemas Agro",
    "description": "Define contrato local-first, versionado e idempotente para integração segura entre produtos ArtiSys Agro.",
    "priceCents": 6957,
    "saleType": "one_time",
    "deliveryMode": "download",
    "artifactName": "integracao-e-contratos-entre-sistemas-agro-v1.0.0.zip",
    "active": false
  },
  {
    "id": "pdv-nexus",
    "productId": "pdv-nexus",
    "name": "PDV Nexus",
    "description": "Frente de caixa e vendas; cadastro de produtos e clientes; leitura de código de barras; vendas por unidade e peso; integração com balanças; controle de estoque, lotes e validade; entrada e inventário; promoções e descontos; pagamentos em dinheiro, Pix, cartão e a prazo; pagamentos mistos; abertura e fechamento de caixa; sangrias; cancelamentos e estornos; controle de operadores e permissões; comprovantes não fiscais; relatórios, indicadores e exportação CSV; backup local.",
    "priceCents": 3990,
    "saleType": "one_time",
    "deliveryMode": "manual",
    "artifactName": null,
    "active": false
  },
  {
    "id": "pdv-artisys-restaurantes",
    "productId": "pdv-artisys-restaurantes",
    "name": "PDV ArtiSys — Bares, Restaurantes e Lanchonetes",
    "description": "Frente de caixa; comandas e mesas; cardápio digital por QR Code; pedidos pelo cliente ou garçom; cozinha digital (KDS); delivery, retirada e balcão; personalização de pedidos; gestão de pizzas, tamanhos, sabores e bordas; fichas técnicas e consumo de ingredientes; controle de estoque e compras; cadastro de clientes e fornecedores; kits, combos e promoções; pagamentos mistos; abertura e fechamento de caixa; devoluções; relatórios gerenciais; impressão não fiscal; operação em rede local,",
    "priceCents": 8990,
    "saleType": "one_time",
    "deliveryMode": "manual",
    "artifactName": null,
    "active": false
  },
  {
    "id": "artisys-sistema-financeiro",
    "productId": "artisys-sistema-financeiro",
    "name": "ArtiSys Sistema Financeiro",
    "description": "Contas a pagar e receber; gestão de contas bancárias; fluxo de caixa; DRE por competência e realizado; dashboard financeiro; importação de extratos CSV, OFX e PDF digital; conciliação bancária determinística; identificação de duplicidades e sugestões de classificação; transferências entre contas; lançamentos recorrentes; centros de custo, tags e rateios; orçamentos e metas; previsto versus realizado; cenários financeiros; projeções e simulações what-if; alertas de vencimento e saldo; a",
    "priceCents": 16990,
    "saleType": "one_time",
    "deliveryMode": "manual",
    "artifactName": null,
    "active": false
  },
  {
    "id": "obra-na-mao",
    "productId": "obra-na-mao",
    "name": "Obra na Mão — Gestão de Obras (Licença Vitalícia)",
    "description": "Cadastro de empresas, clientes e obras; gestão por obra, frente de serviço e etapa; orçamentos; cronograma físico-financeiro e Curva S; medições e acompanhamento de execução; Diário de Obra (RDO); apontamento de equipes, equipamentos e ocorrências; tarefas e pendências; compras, cotações, materiais e estoque; contratos e aditivos; gestão financeira, pagamentos e DRE; RH, funcionários, ponto, folha salarial e benefícios; geração de documentos admissionais; central de documentos; importa",
    "priceCents": 29990,
    "saleType": "one_time",
    "deliveryMode": "manual",
    "artifactName": null,
    "active": false
  }
]);
